### ISSUE TITLE
Google Dialer Not Installed

### ISSUE THREAD

**Issue by elong7681** [jacopotediosi/GoogleDialerMod#1] opened 2021-09-06 22:27 UTC
It keeps telling me that the Google Dialer app isn't installed. I have the newest beta release, I uninstalled the phone app and reinstalled it with no luck

**Comment by jacopotediosi** [comment] 2021-09-06 22:42
> It keeps telling me that the Google Dialer app isn't installed

Hi @elong7681, thanks for reporting your issue.

Could you please confirm that you have installed the Google Dialer app? (https://play.google.com/store/apps/details?id=com.google.android.dialer)? 

If yes, can you please check from Android settings its package name and tell me if it's different from "com.google.android.dialer"?

In order to reproduce this bug I also need to know:
- The version of the Google Dialer you have installed
- Your Android version and the model of your device

**Comment by elong7681** [comment] 2021-09-06 22:50
Yes it is com.google.android.dialer version 69.0.392727699-publicbeta, Android 11, Pixel 5

**Comment by jacopotediosi** [comment] 2021-09-06 23:01
@elong7681 whoops i forgot that Android 11 has a new package visibility filtering.
Please try the new release and tell me if it works for you: https://github.com/jacopotediosi/GoogleDialerMod/releases/tag/v1.1

**Comment by elong7681** [comment] 2021-09-06 23:19
So it allowed me to install it but after opening and force closing the phone app I still don't have the option for recording

**Comment by elong7681** [comment] 2021-09-06 23:27
Also when I open the mod app this 
![Screenshot_20210906-192314](https://user-images.githubusercontent.com/17111151/132265483-ec97c05e-dbae-45b5-a7ee-109c0ab9240e.png)
happens and this happens
![Screenshot_20210906-192329](https://user-images.githubusercontent.com/17111151/132265494-47acd1d2-6cc1-4575-a9ce-d9712c4497d8.png)

**Comment by jacopotediosi** [comment] 2021-09-06 23:28
Ok, at least the "google dialer not installed" error is fixed. Thanks again for your report.
Now, if you close Googledialermod and when you reopen it the switches are still positioned as you put them, it means that the changes have been applied.
Please try to force close and reopen the Dialer app a couple of times and then try to do a call. The recording button should appear.

**Comment by elong7681** [comment] 2021-09-06 23:35
The one switch goes back to gray and I have force closed phone app and opened it multiple times and I have made a phone call and rebooted the phone with no luck

**Comment by jacopotediosi** [comment] 2021-09-06 23:40
Ok, I'll setup an Android 11 emulator and try to replicate. If the switch goes back to gray something is going wrong.
Can you please provide a logcat while clicking switches?
No problem if you can't :)

**Comment by elong7681** [comment] 2021-09-06 23:51
I can get you a logcat, can you tell me how to use the SysLog app to generate one? If not I can do it however you want.

**Comment by jacopotediosi** [comment] 2021-09-07 01:51
Hi @elong7681,
I tested with an Android 11 emulator.
The problem was related to the new Android 11 Scoped Storage.
With release v1.2 it should work now.

**Comment by jacopotediosi** [comment] 2021-09-08 15:27
Hi @elong7681 could you please check if release v1.2 works for you, so I can close this issue?
Thanks a lot :)

**Comment by elong7681** [comment] 2021-09-08 22:44
It doesn't work for me and I'm not sure why, what can I do to help as far as a logcat or whatever you need.

**Comment by jacopotediosi** [comment] 2021-09-09 00:09
> It doesn't work for me and I'm not sure why, what can I do to help as far as a logcat or whatever you need.

Yep, you can help me providing a logcat:

1. Enable developer options in your Android settings
2. Enable ADB in developer options and connect your phone to a PC via USB cable
3. In a terminal paste `adb logcat > logcat.txt`, open GoogleDialerMod, enable the call recording switch and then send me the logcat.txt file

You can found detailed instructions here: https://android.stackexchange.com/questions/33216/how-can-i-get-a-logcat

**Comment by elong7681** [comment] 2021-09-09 00:23
In the SysLog app do I tao take log and then open the mod app and enable the switch or vice versa

**Comment by jacopotediosi** [comment] 2021-09-09 01:13
> In the SysLog app do I tap on the take log button first and then open the mod app and enable the switch or vice versa

First enable the switch and then press the take log button.
To reduce the collected log size, just select the Main Log (logcat), because I don't neew Kernel Log, PStore console etc.

Really, thanks a lot for your cooperation!

**Comment by elong7681** [comment] 2021-09-09 01:13
Ok will do

**Comment by elong7681** [comment] 2021-09-09 01:19
[2021-09-08_21.15.zip](https://github.com/jacopotediosi/GoogleDialerMod/files/7132639/2021-09-08_21.15.zip)

**Comment by jacopotediosi** [comment] 2021-09-09 12:44
Hi @elong7681,
Thanks for your logcat. Unfortunately it did not contain the information I needed to understand the problem.

But I have good news: I have released the [alternative Magisk module to the app](https://github.com/jacopotediosi/GoogleDialerMod-Magisk), which could probably work for you, because Magisk modules usually don't suffer from compatibility issues. 

Anyway, if you still want to help me fix this bug on the app, you would do me a big favor if you could send me the logcat (as you did before) of GoogleDialerMod v1.03 that I just released.

Thank you very much.

**Comment by elong7681** [comment] 2021-09-09 16:56
Ok I will do that for you.

**Comment by elong7681** [comment] 2021-09-09 17:03
[2021-09-09_13.02.zip](https://github.com/jacopotediosi/GoogleDialerMod/files/7138472/2021-09-09_13.02.zip)

**Comment by jacopotediosi** [comment] 2021-09-09 17:27
I see patches are applied correctly to the phenotype database, but I'm not sure the app is clearing correctly the phenotype cache of the google dialer.
Try just to manually delete with a root file explorer the folder /data/data/com.google.android.dialer/files/phenotype and see if opening/closing the dialer a couple of times brings up the option to record calls.

**Comment by jacopotediosi** [comment] 2021-09-09 17:28
If I'm right, it will be difficult to fix the app, but the Magisk module should works fine

**Comment by elong7681** [comment] 2021-09-10 05:07
Neither work for me lol

**Comment by jacopotediosi** [comment] 2022-11-12 15:20
Thanks for the reporting.

It should be fixed with efc58d5d5cdc60d4d6b32e656c5f3fb1e2330224.

Please try [Release v1.04](https://github.com/jacopotediosi/GoogleDialerMod/releases/tag/v1.04) and reopen this issue if the bug persists.

**Closed by jacopotediosi** 2022-11-12 15:20 UTC
